name: CI

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Setup nodejs
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14.x
    - name: Enable executable scripts
      run: chmod +x scripts/build.sh
    - name: Install deps
      run: yarn
    - name: Validate packages
      run: yarn validate

  # release:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Cancel previous runs
  #     uses: styfle/cancel-workflow-action@0.6.0
  #     with:
  #       access_token: ${{ secrets.GITHUB_TOKEN }}

  #   - uses: actions/checkout@v2

  #   - uses: actions/cache@v2
  #     with:
  #       path: '**/node_modules'
  #       key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

  #   - name: Setup nodejs
  #     uses: actions/setup-node@v2.1.4
  #     with:
  #       node-version: 14.x
  #   - name: Validate & publish packages
  #     run: yarn lerna:publish
  #     env:
  #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
